image: node:alpine

stages:
  - install
  - test
  - build
  - deploy-staging
  - deploy-production

.login:
  before_script:
    - echo login from extends

include:
  - "/front/.gitlab-ci.yml"
  - "/back/.gitlab-ci.yml"