.front_rules: &front_rules
  extends: .login
  # only:
  #   refs:
  #     - main
  #   changes:
  #     - front/**/*
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
      - front/**/*
  cache:
    paths:
    - front/node_modules
    policy: pull

install-front:
  <<: *front_rules
  stage: install
  cache:
    paths:
    - front/node_modules
    policy: push
  script: 
    - cd front
    - npm install

unit-test-front:
  <<: *front_rules
  stage: test
  script: 
    - cd front
    - npm run test-unit

functional-test-front:
  <<: *front_rules
  stage: test
  script: 
    - cd front
    - npm run test-functional

build-front:
  <<: *front_rules
  stage: build
  script: 
    - cd front
    - npm run build
  artifacts:
      expire_in: 1 hour
      paths:
        - front/build

deploy-staging-front:
  <<: *front_rules
  stage: deploy-staging
  script:
    - cd front
    - echo deploy to staging
    - ls

deploy-production-front:
  <<: *front_rules
  stage: deploy-production
  script:
    - cd front
    - echo deploy to production
    - echo $NETLIFY_SITE_ID
    - echo $NETLIFY_AUTH_TOKEN
    - ls
